### ISSUE TITLE
OpenSSL cipher errors cause the Rack middleware to crash

### ISSUE THREAD

**Issue by tony-spataro-rs** [rightscale/global_session#12]
global_session is designed to intercept any exception that happens inside the middleware, and save it in the rack env so the Rails integration layer can re-raise it in a way that lets the Rails app code handle the exception.

If the middleware receives a malformed cookie -- specifically, a cookie that's signed by a different authority than is claimed -- it seems the resulting OpenSSL exception doesn't get caught. Instead it aborts the Rack middleware chain and the user sees a nasty "something went horribly wrong" screen.

Someone needs to find out why this type of exception evades the error-handling code.

Here is a stack trace for one such incident.

OpenSSL::PKey::RSAError while reading session cookie: padding check failed /vendor/bundle/ruby/1.8/gems/global_session-2.0.2/lib/global_session/session/v1.rb:296:in /vendor/bundle/ruby/1.8/gems/global_session-2.0.2/lib/global_session/session/v1.rb:296:in /vendor/bundle/ruby/1.8/gems/global_session-2.0.2/lib/global_session/session/v1.rb:61:in /vendor/bundle/ruby/1.8/gems/global_session-2.0.2/lib/global_session/session.rb:36:in `new'/home/rails/right_site/releases/20130726212738/vendor/bundle/ruby/1.8/gems/global_session-2.0.2/lib/global_session/session.rb:36

**Comment by xeger** [comment]
Fixed in v3
